---
- name: Create a PostgreSQL database in AWS RDS
  local_action:
    module: rds
    command: create
    wait: yes
    wait_timeout: 600

    # Our RDS instance gets a unique name to identify it
    instance_name: "{{ simplye_role }}-{{ simplye_instance_name }}"
    tags:
      Environment: "{{ simplye_environment }}"
      Application: "{{ simplye_role }}"

    # Create a new RDS instance
    region: "{{ aws_region }}"
    instance_type: "{{ rds_instance_type }}"
    db_engine: "{{ rds_db_engine }}"
    size: "{{ rds_size }}"
    subnet: "{{ rds_subnet }}"
    vpc_security_groups: "{{ rds_security_groups }}"
    multi_zone: no
    port: 5432

    # Create a database on the instance
    db_name: "{{ psql_db_name }}"
    username: "{{ psql_username }}"
    password: "{{ psql_password }}"
  register: rds

- debug: msg="The db endpoint is {{ rds.instance.endpoint }}"
