---
- name: Create security group for EC2 insance and open SSH port to the ansible control machine
  ec2_group:
    name: "EC2-{{ simplye_role }}-{{ simplye_instance_name }}"
    description: "Firewall rules for the {{ simplye_role }}-{{ simplye_instance_name }} RDS instance"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ admin_ip }}/32"
  register: ec2_sg
- debug: var=ec2_sg.group_id
