---
- name: Generate SSH key pair for ec2
  ec2_key:
    name: "{{ simplye_instance_name }}"
    region: "{{ aws_region }}"
  register: ec2_key

- name: Save private key to local admin's .ssh directory
  copy:
    content: "{{ ec2_key.key.private_key }}"
    dest: "~/.ssh/{{ simplye_instance_name }}.pem"
    mode: 0600
  when: ec2_key.changed
